/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BytesLike
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface FindLibraryInterface extends utils.Interface {
  contractName: "FindLibrary";
  functions: {
    "find(string)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "find", values: [string]): string;

  decodeFunctionResult(functionFragment: "find", data: BytesLike): Result;

  events: {};
}

export interface FindLibrary extends BaseContract {
  contractName: "FindLibrary";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: FindLibraryInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    find(
      input: string,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, boolean] & {
        begin: BigNumber;
        end: BigNumber;
        accepts: boolean;
      }
    >;
  };

  find(
    input: string,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, boolean] & {
      begin: BigNumber;
      end: BigNumber;
      accepts: boolean;
    }
  >;

  callStatic: {
    find(
      input: string,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, boolean] & {
        begin: BigNumber;
        end: BigNumber;
        accepts: boolean;
      }
    >;
  };

  filters: {};

  estimateGas: {
    find(input: string, overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    find(
      input: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
