/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface IUtilInterface extends utils.Interface {
  contractName: "IUtil";
  functions: {
    "substring(string,uint256,uint256)": FunctionFragment;
    "split(string,uint256)": FunctionFragment;
    "tokenize(string,string)": FunctionFragment;
    "copy(string)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "substring",
    values: [string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "split",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "tokenize",
    values: [string, string]
  ): string;
  encodeFunctionData(functionFragment: "copy", values: [string]): string;

  decodeFunctionResult(functionFragment: "substring", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "split", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "tokenize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "copy", data: BytesLike): Result;

  events: {};
}

export interface IUtil extends BaseContract {
  contractName: "IUtil";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IUtilInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    substring(
      _str: string,
      begin: BigNumberish,
      end: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    split(
      _str: string,
      pos: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string, string]>;

    tokenize(
      _str: string,
      _delim: string,
      overrides?: CallOverrides
    ): Promise<[string[]]>;

    copy(str: string, overrides?: CallOverrides): Promise<[string]>;
  };

  substring(
    _str: string,
    begin: BigNumberish,
    end: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  split(
    _str: string,
    pos: BigNumberish,
    overrides?: CallOverrides
  ): Promise<[string, string]>;

  tokenize(
    _str: string,
    _delim: string,
    overrides?: CallOverrides
  ): Promise<string[]>;

  copy(str: string, overrides?: CallOverrides): Promise<string>;

  callStatic: {
    substring(
      _str: string,
      begin: BigNumberish,
      end: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    split(
      _str: string,
      pos: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string, string]>;

    tokenize(
      _str: string,
      _delim: string,
      overrides?: CallOverrides
    ): Promise<string[]>;

    copy(str: string, overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    substring(
      _str: string,
      begin: BigNumberish,
      end: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    split(
      _str: string,
      pos: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    tokenize(
      _str: string,
      _delim: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    copy(str: string, overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    substring(
      _str: string,
      begin: BigNumberish,
      end: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    split(
      _str: string,
      pos: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    tokenize(
      _str: string,
      _delim: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    copy(str: string, overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
